apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: LoadBalancer
  externalIPs:
    - 10.99.80.102  
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: phpmyadmin

